# Generated by Django 3.1.5 on 2021-01-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('is_administration', 'Administration'), ('is_doctor', 'Doctor'), ('is_reception', 'Receptionist')]},
        ),
    ]
